### ISSUE TITLE
Missing value-mappings: Dataset.theme (CBS)

### ISSUE THREAD

**Issue by WterBerg** [dataoverheid/donlsync-mappings#14]
```
# 2021-08-16

Dataset, theme, arbeidsmarkt mobiliteit 
Dataset, theme, bevolking en huishoudens 
Dataset, theme, dienstenprijzen 
Dataset, theme, inkomen van huishoudens, personen,  2006
Dataset, theme, personen met aow-uitkering
```

**Comment by patricksttan** [comment]
Weet je zeker dat die moeten? Ik zag elk van deze missing values namelijk in de file, maar met hoofdletter.

**Comment by lbercken** [comment]
@patricksttan Ja! De mappings die donlsync uitvoert zijn hoofdletter gevoelig. Deze waardes met kleine letter moeten dus ook in de mapping.
